function(addExample NAME DESCRIPTION)
    option(${NAME} ${DESCRIPTION} 1)
    if(${NAME})
        add_subdirectory("examples/${NAME}")
    endif()
endFunction()

set(ASTYLE_BINARY "astyle" CACHE PATH "Path to astyle binary to format the code by \"ninja format\"")
set(ASTYLE_OPTIONS -A1 -C -n -k3 -p -U -xg -r -o CACHE STRING "Astyle options used by \"ninja format\"")
add_custom_target(format WORKING_DIRECTORY ${CMAKE_PROJECT_DIR})
add_custom_command(TARGET format PRE_BUILD COMMAND ${ASTYLE_BINARY} ${CMAKE_SOURCE_DIR}/*.cpp,*.h,*.cu,*.cxx,*.cppm --exclude=external --exclude=build -i ${ASTYLE_OPTIONS})
