name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: ./scripts/buildOnUbuntu-24_04.sh
